<?php
use Drupal\Core\Messenger;
use Drupal\Core\Url;
use Drupal\user\UserInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\user\Entity\User;
use Drupal\commerce_cart\CartManagerInterface;
use Drupal\Core\Messenger\MessengerTrait;
use Drupal\Core\StringTranslation\StringTranslationTrait;
use Drupal\commerce_order\Entity\Order;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_cron().
 */
function aydinlik_cron_cron() {
  /* $users = User::loadMultiple();
  $dateTime = \DateTime::createFromFormat('Y-m-d',date('Y-m-d'));
  $today = $dateTime->format('Y-m-d');
  foreach($users as $user) {
      $user_name = $user->field_adiniz->value;
      $user_surname = $user->field_soyadiniz->value;
      if ($user->field_abonelik_referans_kodu->value != NULL){
          $src = $user->field_abonelik_referans_kodu->value;
          if ($user->field_abonelik_bitis_tarihi[0]->value <= $today ) {
            $request = new \Iyzipay\Request\Subscription\SubscriptionDetailsRequest();
            $request->setSubscriptionReferenceCode($src);
            $result = \Iyzipay\Model\Subscription\SubscriptionDetails::retrieve($request,Drupal\iyzipay\Config::options());
            $orders = $result->getOrders();
            $last_order = end($orders);
            $last_payment = $last_order->paymentAttempts[0]->paymentStatus;
            $ppn = $result->getPricingPlanName(); //$ppn is pricing plan name
            //$order_created = date('Y-m-d',substr($result->getCreatedDate(),0,10));
        if ($last_payment == 'SUCCESS') {
          if (str_contains ($ppn, 'Aylık')) {
            $fabt = date('Y-m-d', strtotime('1 month',strtotime($user->field_abonelik_bitis_tarihi[0]->value)));
            $user->field_abonelik_bitis_tarihi[0]->value = $fabt;
            $user->addRole('abone');
            $user->save();
            $message = $user_name. ' '. $user_surname. ' '.  'Aylık abonelik başarılı bir şekilde uzatılmıştır.';
            \Drupal::logger('aydinlik_cron')->notice($message);
          }
          if (str_contains ($ppn, 'Yıllık')) {
              $fabt = date('Y-m-d', strtotime('1 month',strtotime($user->field_abonelik_bitis_tarihi[0]->value)));
              $user->field_abonelik_bitis_tarihi[0]->value = $fabt;
              $user->addRole('abone');
              $user->save();
              $message = $user_name. ' '. $user_surname. ' '. 'Yıllık abonelik başarılı bir şekilde uzatılmıştır.';
              \Drupal::logger('aydinlik_cron')->notice($message);
            }
        }
        else {
            $user->field_abonelik_durumu->value = 'Yenileme bekliyor';
            $user->removeRole('abone');
            $user->save();
            $message = $user_name. ' '. $user_surname. ' '. 'Aboneliğin uzatılması sırasında bir hata oluştu. Lütfen abone ile iletişime geçiniz.';
            \Drupal::logger('aydinlik_cron')->error($message);
        }
      }
    }
  } */
  $rCodes = array("a46d8cb4-2f9e-4d83-bc6e-1ff86db7af0f"
  ,"2bf1e69a-35dc-4e0c-a1af-7da32e8be2eb"
  ,"3d746b26-3a5c-49dc-a41e-d42f187097f7"
  ,"cda02ee9-02a2-4d1b-b48d-bb26911ea5e2"
  ,"31e4c194-9a69-45ae-ae93-77366f352f01"
  ,"210c7c2f-ba97-474b-a7a4-bba81b003a60"
  ,"2b686200-ca67-476c-ab46-f32bce0b430b"
  ,"d7586d99-fcf1-4605-8012-5070f28a4860"
  ,"590ce658-a5bf-4028-8e4d-e6215778266c"
  ,"03b01f3a-da39-44fd-b0df-29310753c7e2"
  ,"9f643483-aedf-4ba6-9e69-a253ea9af81a"
  ,"6ab3a9f4-1906-4317-88db-02f77432601c"
  ,"f674930b-3798-4ba2-97b3-fe12bc55e9cc"
  ,"ea2d0310-25b7-46ff-a4c4-f2e0dd59d767"
  ,"0dc394c3-9c54-45a3-93f0-a3ed8aadef2e"
  ,"f6ffa7ae-d053-4a2a-ad60-bf921d03e2e2"
  ,"2f2ad636-3a61-4ecd-b6ea-1831c6181399"
  ,"d453ab5d-74f0-4bc2-97ce-254641d56aa6"
  ,"469f6112-26ff-4281-9599-eff4fcb94e0e"
  ,"88159b76-58ae-45e8-9da9-90db8f5e307c"
  ,"e1647cff-20dc-4148-8122-f6296a5657b0"
  ,"7f513ae8-e153-430c-80c8-7896e88cca8c"
  ,"4d88a033-cd10-4885-9730-0b270605f477"
  ,"317da345-aad9-4a66-b4e1-f451df3bcf39"
  ,"8a04e76e-b280-4ca2-b5ea-0667a523a4a2"
  ,"127ed2a5-6a70-4e0b-b9fb-0ec1b3722fce"
  ,"69fd6bb8-4b2b-427f-95fb-fef60389e0bc"
  ,"cec9d80c-53d3-4a1d-a85f-32069772a52b"
  ,"43a4d951-2abe-43ed-98e0-36ba9f3672f1"
  ,"00b170b0-89a5-41e9-a0f9-96278846e3b0"
  ,"39b78fe3-9dbf-431d-b95b-0a2a3f409681"
  ,"d4494125-2e80-4b02-a447-e96754badad6"
  ,"bcfe5683-8b1e-41fc-b2a8-1b87487e34b9"
  ,"bda9758e-ab99-4453-8c96-204cdfcbfa9c"
  ,"c0ebc195-626c-4e10-8ba1-0c8245679792"
  ,"3010c510-8318-489c-a923-051b296488a7"
  ,"3d77b851-699b-4c5d-b8a4-d564e2a884f3"
  ,"f37aba17-50cc-4457-a82d-1515a878ef08"
  ,"080a995c-d011-47c7-8bc2-d06f5870bfee"
  ,"ab670b38-7949-4136-8e95-3a94c8a1e49a"
  ,"b552a7e9-d085-4b0c-b59e-12892a3f3ed1"
  ,"2678b6c9-7ded-43cb-8891-40c09d4e1023"
  ,"eb611aaa-f10b-4758-8c6c-20b9f415cffd"
  ,"5efde6f2-2457-476c-9fc8-ce45558b9915"
  ,"0ef4ace8-47c5-431c-9cec-3b4055338567"
  ,"9c11e7f7-2d66-4c69-bae0-453d3f3287d6"
  ,"f25dd1fb-e755-42cc-9e3a-76370b121205"
  ,"c67ce520-cd75-4cb6-a108-f922dcdbffd6"
  ,"3aa1274e-a3b4-459f-a58c-159c6169a3ee"
  ,"76984cb1-5528-491d-80ae-0eba882b1e66"
  ,"229d5dda-874e-425e-b112-6fbc210c3dc2");
  
  foreach ($rCodes as $rCode) {
  $request = new \Iyzipay\Request\Subscription\SubscriptionDetailsRequest();
  $request->setSubscriptionReferenceCode($rCode);
  $result = \Iyzipay\Model\Subscription\SubscriptionDetails::retrieve($request,\Drupal\iyzipay\Config::options());
  if ($result->getStatus() == 'success') {
  $email = $result->getCustomerEmail();
  $productName = $result->getProductName();
  dpm($email.' '.$productName);
  
  $users = User::loadMultiple();
  foreach ($users as $user) {
    $umail = $user->mail->value;
    if ($email == $umail) {
      dpm('E-postalar aynı'. ' ' . $email.'='.$umail);
      if ($user->field_abonelik_suresi->target_id == '1354') {
    $sType = 'Aylık Abonelik';
  }
  if ($user->field_abonelik_suresi->target_id =='1360') {
    $sType = 'Aylık Abonelik - Öğrenci';
  }
  if ($user->field_abonelik_suresi->target_id == '1364') {
    $sType = 'Yıllık Abonelik - Avrupa';
  }
  if ($user->field_abonelik_suresi->target_id == '1365') {
    $sType = 'Yıllık Abonelik - Avrupa Dışı';
  }
  if ($user->field_abonelik_suresi->target_id == '1359') {
    $sType = 'Yıllık Abonelik - Öğrenci';
  }
  if ($user->field_abonelik_suresi->target_id == '1355') {
    $sType = '3 Aylık Abonelik';
  }
  if ($user->field_abonelik_suresi->target_id == '1356') {
    $sType = '6 Aylık Abonelik';
  }
  if ($user->field_abonelik_suresi->target_id == '1358') {
    $sType = 'Yıllık Abonelik';
  }
  if ($productName != $sType) {
      $name = $user->field_adiniz->value;
      $surname = $user->field_soyadiniz->value;
      $ns = $name.' '.$surname;
  $request = new \Iyzipay\Request\Subscription\SubscriptionCancelRequest();
  $request->setLocale("tr");
  $request->setSubscriptionReferenceCode($rCode);
  $result = \Iyzipay\Model\Subscription\SubscriptionCancel::cancel($request,\Drupal\iyzipay\Config::options());
  $message = $ns.' kullanıcısının yanlış aboneliği iptal edilmiştir.';
  \Drupal::logger('aydinlik_cron')->notice($message);
           }
        }
      }
    }
  }
}