<?php
use Drupal\Core\Messenger;
use Drupal\Core\Url;
use Drupal\user\UserInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\user\Entity\User;
use Drupal\commerce_cart\CartManagerInterface;
use Drupal\Core\Messenger\MessengerTrait;
use Drupal\Core\StringTranslation\StringTranslationTrait;
use Drupal\commerce_order\Entity\Order;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_cron().
 */
function aydinlik_cron_cron() {
  /* $users = User::loadMultiple();
  $dateTime = \DateTime::createFromFormat('Y-m-d',date('Y-m-d'));
  $today = $dateTime->format('Y-m-d');
  foreach($users as $user) {
      $user_name = $user->field_adiniz->value;
      $user_surname = $user->field_soyadiniz->value;
      if ($user->field_abonelik_referans_kodu->value != NULL){
          $src = $user->field_abonelik_referans_kodu->value;
          if ($user->field_abonelik_bitis_tarihi[0]->value <= $today ) {
            $request = new \Iyzipay\Request\Subscription\SubscriptionDetailsRequest();
            $request->setSubscriptionReferenceCode($src);
            $result = \Iyzipay\Model\Subscription\SubscriptionDetails::retrieve($request,Drupal\iyzipay\Config::options());
            $orders = $result->getOrders();
            $last_order = end($orders);
            $last_payment = $last_order->paymentAttempts[0]->paymentStatus;
            $ppn = $result->getPricingPlanName(); //$ppn is pricing plan name
            //$order_created = date('Y-m-d',substr($result->getCreatedDate(),0,10));
        if ($last_payment == 'SUCCESS') {
          if (str_contains ($ppn, 'Aylık')) {
            $fabt = date('Y-m-d', strtotime('1 month',strtotime($user->field_abonelik_bitis_tarihi[0]->value)));
            $user->field_abonelik_bitis_tarihi[0]->value = $fabt;
            $user->addRole('abone');
            $user->save();
            $message = $user_name. ' '. $user_surname. ' '.  'Aylık abonelik başarılı bir şekilde uzatılmıştır.';
            \Drupal::logger('aydinlik_cron')->notice($message);
          }
          if (str_contains ($ppn, 'Yıllık')) {
              $fabt = date('Y-m-d', strtotime('1 month',strtotime($user->field_abonelik_bitis_tarihi[0]->value)));
              $user->field_abonelik_bitis_tarihi[0]->value = $fabt;
              $user->addRole('abone');
              $user->save();
              $message = $user_name. ' '. $user_surname. ' '. 'Yıllık abonelik başarılı bir şekilde uzatılmıştır.';
              \Drupal::logger('aydinlik_cron')->notice($message);
            }
        }
        else {
            $user->field_abonelik_durumu->value = 'Yenileme bekliyor';
            $user->removeRole('abone');
            $user->save();
            $message = $user_name. ' '. $user_surname. ' '. 'Aboneliğin uzatılması sırasında bir hata oluştu. Lütfen abone ile iletişime geçiniz.';
            \Drupal::logger('aydinlik_cron')->error($message);
        }
      }
    }
  } */

$rCodes = array("5366ceb0-36c9-4f53-a13c-b352e070dc8b"
,"bb440768-24a7-4031-add6-2b535be45ff6"
,"9f2831b5-2ad7-4cf0-8dea-ecdf408079f6"
,"d615b72b-d741-4351-a08e-a5f643be6535"
,"7130af07-f504-4f72-befa-0914aa185b87"
,"5c32e222-8666-408a-987a-061ac92f0610"
,"dd56de3f-fad8-42e2-860a-e15f19c0dda5"
,"64f2f803-afe8-4528-9029-71d99c19cf66"
,"34d11a9e-94d1-4c62-8d6b-d56115eaafad"
,"491a4602-c0a5-4018-a04a-2cc381a1493d"
,"b36f659f-9589-457a-b3e7-6aac7319a9f1"
,"1da8ecaa-300f-4a96-b5ee-0ecc7d44d222"
,"c01ee385-2688-435c-a0d9-7f27237ecc05"
,"bf88fdcb-a10d-49e2-839e-b4ccf1a6a2bb"
,"720841af-bbec-4d25-94c9-9bee6cbf2281"
,"b53939b0-9492-4cf8-8196-71ae275efd86"
,"4cefa0f8-9f85-4241-a569-42c594f67290"
,"2bd802b0-a59a-487f-87d2-c04097dad5cf"
,"928592dd-6405-4c83-b35f-64ca444e78b9"
,"ac2ea746-d5ad-455d-b758-1925b0bb6634"
,"f2abf13a-dc64-4082-9cbe-706a84f5ef3d"
,"149bdfc0-82d5-4c8f-9166-3bd9057e3dfc"
,"6672d6fd-149b-43a2-bd32-37993a57b507"
,"36b2c6ea-dc09-4cc8-854e-a11f07fd363b"
,"05de12f4-2c09-4135-b3f8-39665637c601"
,"e14f1534-6d88-4f02-8db9-d0cc2a7f2fdb"
,"f88e51c5-e32a-4ac6-ac02-7794494a5edc"
,"aa4067c9-ea34-4f85-a488-dbc39bb541ba"
,"9c54e11a-5db9-47f4-a5b0-fef05f55aabb"
,"7986eba3-86e9-4b04-915e-858be82e6515"
,"f9765b06-006c-4747-88f1-4e6aeb064c11"
,"e37f7006-6ac5-4275-8be3-134d627f87ea"
,"d4f6d372-84d7-4bf5-bd39-b3df17c72850"
,"e628d251-72b7-42e2-b244-d6a21dd7c588"
,"560b0599-7eff-484a-b60c-10a180f8ea25"
,"86810d25-ef01-475e-9ada-31d53bbf9a49"
,"dcab5f8e-5cd7-482a-bf8f-503eaa209875"
,"0f38da2f-fe02-4c78-8f84-5e7a490d7426"
,"c10462e4-f020-4de2-b8aa-0c6427a9a36b"
,"abb129f1-586f-47e4-8599-545b81f82e71"
,"4315138e-33ef-4077-a821-e46303c4bbd7"
,"cec45263-cbae-4be3-995e-ae0f43d365c3"
,"0f929398-455d-45fa-8b0f-46f405d90027"
,"d0200690-368b-46c6-ba8b-49295b8b5241"
,"7b3847b6-8c80-4fa0-9d37-ac2ca0953cae"
,"8802fade-ba14-40c1-bd29-79212bea8569"
,"141cf750-53c4-4739-b5e9-75bd2f4e463d"
,"b2256696-5873-4747-b40b-07947491f517"
,"ef96df72-6b57-4a65-a46e-c72bbd8d9c59");

foreach ($rCodes as $rCode) {
$request = new \Iyzipay\Request\Subscription\SubscriptionDetailsRequest();
$request->setSubscriptionReferenceCode($rCode);
$result = \Iyzipay\Model\Subscription\SubscriptionDetails::retrieve($request,\Drupal\iyzipay\Config::options());
if ($result->getStatus() == 'success') {
$email = $result->getCustomerEmail();
$productName = $result->getProductName();
dpm($email.' '.$productName);

$users = User::loadMultiple();
foreach ($users as $user) {
  $umail = $user->mail->value;
  if ($email == $umail) {
    dpm('E-postalar aynı'. ' ' . $email.'='.$umail);
if ($user->field_abonelik_suresi->target_id == '1354') {
  $sType = 'Aylık Abonelik';
}
if ($user->field_abonelik_suresi->target_id =='1360') {
  $sType = 'Aylık Abonelik Öğrenci';
}
if ($user->field_abonelik_suresi->target_id == '1364') {
  $sType = 'Yıllık Abonelik Avrupa';
}
if ($user->field_abonelik_suresi->target_id == '1365') {
  $sType = 'Yıllık Abonelik Avrupa Dışı';
}
if ($user->field_abonelik_suresi->target_id == '1359') {
  $sType = 'Yıllık Abonelik Öğrenci';
}
if ($user->field_abonelik_suresi->target_id == '1355') {
  $sType = '3 Aylık Abonelik';
}
if ($user->field_abonelik_suresi->target_id == '1356') {
  $sType = '6 Aylık Abonelik';
}
if ($user->field_abonelik_suresi->target_id == '1358') {
  $sType = 'Yıllık Abonelik';
}
if ($productName != $sType) {
    $name = $user->field_adiniz->value;
    $surname = $user->field_soyadiniz->value;
    $ns = $name.' '.$surname;
$request = new \Iyzipay\Request\Subscription\SubscriptionCancelRequest();
$request->setLocale("tr");
$request->setSubscriptionReferenceCode($rCode);
$result = \Iyzipay\Model\Subscription\SubscriptionCancel::cancel($request,\Drupal\iyzipay\Config::options());
$message = $ns.' kullanıcısının yanlış aboneliği iptal edilmiştir.';
\Drupal::logger('aydinlik_cron')->notice($message);
         }
      }
    }
  }
}
}